language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: yMHPZjwVMbWLaExFJ6w9+4XrquImKFzyRJjvUS+1vbUOZ1Vd9WO2/83kxCXG7Hah0TqZ/9A2QokxYiRtkijpfuh53Ni8vrwR3ej581X1GFczSgAvxC0GC0ZVaelkNYEPJe7rfdUpYKRN+MmMfe24hCmXtQhVDSRq0lLa/ydCUQLeVomRkQpw3NGhLFvY28ePEb//UZOaGVIiuIjzGOz/SROy8K09ypU9Lr37Uk6LAAUgfXbsAJblWWmObGZ4qRlNIlHsAXmWtKYQDb3qweFN/Lpc+uF/15iAfBQCbM8d1fSTlMlVy2U/BPufWlIvDcK69VAFoC9ALGkjXoNTQrfMAfZA001dUXfccf5ISTzlyZTOldGZXMgYytA3QlOu/VVRqKARE88Zvqz5lk+En1yO656gXXYSUBomXy3aN6TQ42+rfim8AZ/60BPReiMPQ5uOVO5uEbqAsy+Hr+ulHhIQYqqFtxRfDeQVruOPitqDi2DYRiJye40v73bqJYORxUWfbNPyCbSRt5NR4n0DOUKOxQ89NJVgA/42l7aASkoNmVNDHkfU11813S5Lwkq6uWOh469KrOMN07gXv9wM2GDPFF7EGi/UCfp6WLxapNlYxSsOiARNVXYbtsev9OZO/xRXqJ8m9q0fnmocXKrWUFY2FN8P5oKqdJb04xqnZbk0a44=
  app: radiant-scrubland
  on:
    repo: ianmcdermott/art-app
services: 
- mongodb